
name: Benchmarking

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Run benchmarking
      run: |
        python benchmark.py
    - name: Add benchmarking image
      uses: EndBug/add-and-commit@v9
      with:
        add: benchmarking.png
        message: "ran benchmarking"
        committer_name: GitHub Actions
        committer_email: actions@github.com
        push: true